import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {Toast, ToastProviderContainer} from "~/components/global/toast";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-white h-screen">
          <ToastProviderContainer>
            {children}
            <Toast />
          </ToastProviderContainer>
        </div>
      </body>
    </html>
  )
}
